import Head from "next/head";
import { useState, useEffect } from "react";
import Image from "next/image";
import style from "../styles/Home.module.css";

export default function Home() {
  const [date] = useState(new Date().toDateString().slice(0, 10));
  console.log(date);

  return (
    <div className={style.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className=''>
        <header>
          <h1 className={style.date}>{date}</h1>

          <div>
            <h3 className={style.today}>Today</h3>
            {/* user here and flex */}
          </div>
        </header>

        <section className={style.section_container}>
          <div className={style.image_container}>
            <img
              src='pubg_new_state.jpg'
              alt='new state'
              className={style.home_img}
            />
          </div>
        </section>
      </main>

      <footer className={""}></footer>
    </div>
  );
}
