import Head from "next/head";
import Link from "next/link";
import Button from "@mui/material/Button";
import LoginIcon from "@mui/icons-material/Login";
import dashboardStyles from "../../styles/dashboard/Index.module.css";

const Login = () => {
  return (
    <div className={`${dashboardStyles.dashboard} dark:bg-gray-900`}>
      <Head>
        <title>Login / Sign Up</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <main
        className={`flex items-center justify-center flex-col ${dashboardStyles.height}`}
      >
        <div className=''>
          <p>Welcome</p>
        </div>

        <Link href='/dashboard/login'>
          <a>
            <Button variant='contained' endIcon={<LoginIcon />}>
              Login
            </Button>
          </a>
        </Link>
      </main>
    </div>
  );
};

export default Login;
