import Head from "next/head";
import Box from "@mui/material/Box";
import TextField from "@mui/material/TextField";

import dashboardStyles from "../../styles/dashboard/Index.module.css";

const Login = () => {
  return (
    <div className={`${dashboardStyles.dashboard} dark:bg-gray-100 text-black`}>
      <Head>
        <title>Login / Sign Up</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <main>
     
      </main>
    </div>
  );
};

export default Login;
